name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller reportlab

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name KittySudoku kittys_robot_gui.py

    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: KittySudoku_exe
        path: dist/KittySudoku.exe
